### ISSUE TITLE
Système politique suisse

### ISSUE THREAD

**Issue by Nicolapps** [Drulac/State#1]
The Swiss political system is very interesting ! Take a look :

https://www.youtube.com/watch?v=RIoMTXnLlOo

**Comment by Drulac** [comment]
On va échanger en anglais, pour augmenter le nombre de contributions :)

**Comment by Nicolapps** [comment]
@Drulac Why don't you rename the repo ?

**Comment by Drulac** [comment]
I have rename the repo ;)
